services:
  - type: web
    name: ncip-region-1
    runtime: docker
    region: oregon
    repo: https://github.com/patacsilpam/NCIP-Region-1-website
    plan: free
    envVars:
      - key: WORDPRESS_DB_HOST
        value: ${wordpress-db.PRIVATE_HOST}
      - key: WORDPRESS_DB_NAME
        value: wordpress
      - key: WORDPRESS_DB_USER
        value: root
      - key: WORDPRESS_DB_PASSWORD
        value: ""
      - key: WP_SITE_TITLE
        value: "National Commission on Indigenous Peoples Region 1"

  - type: pserv
    name: wordpress-db
    runtime: docker
    repo: https://github.com/patacsilpam/NCIP-Region-1-website
    plan: free
